# Generated by Django 2.2 on 2019-05-04 18:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agriculture_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مقترح زراعي', help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
            ],
            options={
                'verbose_name': 'مقترحات زراعية',
                'verbose_name_plural': 'مقترحات زراعية',
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Complaint_reply', models.TextField(default='لم يتم الرد بعد ...', verbose_name='الرد على الشكوى')),
                ('Complaint_title', models.CharField(help_text='عنوان الشكوى', max_length=500, verbose_name='عنوان الشكوى')),
                ('Complaint_writer', models.CharField(help_text='اسم المواطن', max_length=200, verbose_name='اسم المواطن')),
                ('Complaint_writer_id', models.CharField(help_text='الرقم القومي', max_length=200, verbose_name='الرقم القومي')),
                ('Complaint_writer_phone', models.CharField(help_text='رقم الهاتف', max_length=200, verbose_name='رقم الهاتف')),
                ('Complaint_email', models.EmailField(help_text='البريد الإلكتروني', max_length=254, verbose_name='البريد الإلكتروني')),
                ('Complaint_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ')),
                ('Complaint_content', models.TextField(default='محتوى الشكوى ...', verbose_name='محتوى الشكوى')),
            ],
            options={
                'verbose_name': 'شكاوى المواطنين',
                'verbose_name_plural': 'شكاوى المواطنين',
                'ordering': ['Complaint_reply', 'Complaint_title', 'Complaint_writer', 'Complaint_writer_id', 'Complaint_writer_phone', 'Complaint_email', 'Complaint_date', 'Complaint_content'],
            },
        ),
        migrations.CreateModel(
            name='Development_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مقترح تنموي', help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
            ],
            options={
                'verbose_name': 'مقترحات تنموية',
                'verbose_name_plural': 'مقترحات تنموية',
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Industrial_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مقترح صناعي', help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
            ],
            options={
                'verbose_name': 'مقترحات صناعية',
                'verbose_name_plural': 'مقترحات صناعية',
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='مكان الهيئة', max_length=500, verbose_name='مكان الهيئة')),
            ],
            options={
                'verbose_name': 'مكان الهيئة',
                'verbose_name_plural': 'مكان الهيئة',
                'ordering': ['location'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_Title', models.CharField(default='خبر عاجل', help_text='أدخل عنوان الخبر', max_length=200, verbose_name='عنوان الخبر')),
                ('news_Img', models.ImageField(blank=True, default='', help_text='قم بتحميل صورة الخبرة', null=True, upload_to='home/static/img', verbose_name='صورة الخبر')),
                ('news_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='أدخل الوقت والتاريخ', null=True, verbose_name='الوقت والتاريخ')),
                ('news_Content', models.TextField(default='Urgent news', help_text='أدخل محتوى الخبر', verbose_name='محتوى الخبر')),
            ],
            options={
                'verbose_name': 'أخبار أهل الصعيد',
                'verbose_name_plural': 'أخبار أهل الصعيد',
                'ordering': ['news_Title', 'news_Img', 'news_Content'],
            },
        ),
        migrations.CreateModel(
            name='News2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_Title', models.CharField(default='خبر عاجل', help_text='أدخل عنوان الخبر', max_length=200, verbose_name='عنوان الخبر')),
                ('news_Img', models.ImageField(blank=True, default='', help_text='قم بتحميل صورة الخبرة', null=True, upload_to='home/static/img', verbose_name='صورة الخبر')),
                ('news_Date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='أدخل الوقت والتاريخ', null=True, verbose_name='الوقت والتاريخ')),
                ('news_Content', models.TextField(default='Urgent news', help_text='أدخل محتوى الخبر', verbose_name='محتوى الخبر')),
            ],
            options={
                'verbose_name': 'أخبار الهيئة',
                'verbose_name_plural': 'أخبار الهيئة',
                'ordering': ['news_Title', 'news_Img', 'news_Content'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Governing_Council',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مجلس الإدارة', help_text='اللقب', max_length=300, verbose_name='اللقب أو الدرجة')),
                ('name', models.CharField(default='عضو مجلس الادارة', help_text='الاسم', max_length=400, verbose_name='الاسم')),
            ],
            options={
                'verbose_name': 'مجلس الإدارة',
                'verbose_name_plural': 'مجلس الإدارة',
                'ordering': ['title', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Law',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('law_title', models.CharField(default='اسم القانون', help_text='الوثيقة', max_length=1000, verbose_name='عنوان الوثيقة')),
                ('law_date', models.DateField(default=django.utils.timezone.now, help_text='التاريخ', verbose_name='تاريخ الوثيقة')),
                ('law_content', models.FileField(default='محتوى القانون', help_text='ملف الوثيقة', upload_to='home/static/docs', verbose_name='ملف الوثيقة')),
            ],
            options={
                'verbose_name': 'قوانين ولوائح',
                'verbose_name_plural': 'قوانين ولوائح',
                'ordering': ['law_title', 'law_date', 'law_content'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Leader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_leader', models.CharField(default='قيادات الهيئة', help_text='قيادات الهيئة', max_length=300, verbose_name='قيادات الهيئة')),
            ],
            options={
                'verbose_name': 'قيادات الهيئة',
                'verbose_name_plural': 'قيادات الهيئة',
                'ordering': ['organization_leader'],
            },
        ),
        migrations.CreateModel(
            name='Organization_Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_task', models.TextField(default='مهام الهيئة', help_text='مهام الهيئة', verbose_name='مهام الهيئة')),
            ],
            options={
                'verbose_name': 'مهام الهيئة',
                'verbose_name_plural': 'مهام الهيئة',
                'ordering': ['organization_task'],
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(help_text='تليفونات الهيئة', max_length=200, verbose_name='تليفونات الهيئة')),
            ],
            options={
                'verbose_name': 'تليفونات الهيئة',
                'verbose_name_plural': 'تليفونات الهيئة',
                'ordering': ['phone'],
            },
        ),
        migrations.CreateModel(
            name='Project_Ended',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='اسم المشروع', help_text='اسم المشروع', max_length=500, verbose_name='اسم المشروع')),
                ('project_description', models.TextField(default='وصف المشروع', help_text='وصف المشروع', verbose_name='وصف المشروع')),
            ],
            options={
                'verbose_name': 'مشروعات تم تنفيذها',
                'verbose_name_plural': 'مشروعات تم تنفيذها',
                'ordering': ['project_name', 'project_description'],
            },
        ),
        migrations.CreateModel(
            name='Project_Planned',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='اسم المشروع', help_text='اسم المشروع', max_length=500, verbose_name='اسم المشروع')),
                ('project_description', models.TextField(default='وصف المشروع', help_text='وصف المشروع', verbose_name='وصف المشروع')),
            ],
            options={
                'verbose_name': 'مشروعات مخططه',
                'verbose_name_plural': 'مشروعات مخططه',
                'ordering': ['project_name', 'project_description'],
            },
        ),
        migrations.CreateModel(
            name='Project_UnderProcessing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(default='اسم المشروع', help_text='اسم المشروع', max_length=500, verbose_name='اسم المشروع')),
                ('project_description', models.TextField(default='وصف المشروع', help_text='وصف المشروع', verbose_name='وصف المشروع')),
            ],
            options={
                'verbose_name': 'مشروعات تحت التنفيذ',
                'verbose_name_plural': 'مشروعات تحت التنفيذ',
                'ordering': ['project_name', 'project_description'],
            },
        ),
        migrations.CreateModel(
            name='Service_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مقترح خدمي', help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
            ],
            options={
                'verbose_name': 'مقترحات خدمية',
                'verbose_name_plural': 'مقترحات خدمية',
                'ordering': ['title', 'content'],
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_img', models.ImageField(blank=True, help_text='قم برفع الصورة', null=True, upload_to='home/static/img/slideShow', verbose_name='الصورة')),
                ('slide_caption', models.CharField(default='Caption Text', help_text='اكتب التعليق - التعقيب أسفل الصورة', max_length=200, verbose_name='تعليق على الصورة')),
                ('slide_album', models.CharField(default='Tourist Album', help_text='أدخل اسم الألبوم(مثال : سياحية - فرعونية - إسلامية - قبطية  وهكذا ...)', max_length=200, verbose_name='اسم الألبوم')),
            ],
            options={
                'verbose_name': 'معرض الصور',
                'verbose_name_plural': 'معرض الصور',
                'ordering': ['slide_img'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suggestion_title', models.CharField(help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('suggestion_writer', models.CharField(help_text='اسم المواطن', max_length=200, verbose_name='اسم المواطن')),
                ('suggestion_email', models.EmailField(help_text='البريد الإلكتروني', max_length=254, verbose_name='البريد الإلكتروني')),
                ('suggestion_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='التاريخ', null=True, verbose_name='الوقت والتاريخ')),
                ('suggestion_content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
                ('suggestion_kind', models.CharField(choices=[('option1', 'مقترحات زراعية'), ('option2', 'مقترحات صناعية'), ('option3', 'مقترحات تنموية'), ('option4', 'مقترحات خدمية'), ('option5', 'مقترحات سياحية')], default=('option2', 'مقترحات صناعية'), help_text='نوع الإقتراح', max_length=100, verbose_name='نوع الإقتراح')),
            ],
            options={
                'verbose_name': 'مقترحات المواطنين',
                'verbose_name_plural': 'مقترحات المواطنين',
                'ordering': ['suggestion_title', 'suggestion_writer', 'suggestion_email', 'suggestion_date', 'suggestion_content'],
            },
        ),
        migrations.CreateModel(
            name='Tourist_Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='مقترح سياحي', help_text='عنوان الإقتراح', max_length=500, verbose_name='عنوان الإقتراح')),
                ('content', models.TextField(default='محتوى الإقتراح ...', verbose_name='محتوى الإقتراح')),
            ],
            options={
                'verbose_name': 'مقترحات سياحية',
                'verbose_name_plural': 'مقترحات سياحية',
                'ordering': ['title', 'content'],
            },
        ),
    ]
